apiVersion: v1
kind: ConfigMap
metadata:
  name: koord-scheduler-config
  namespace: {{ .Values.installation.namespace }}
data:
  koord-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceLock: leases
      resourceName: koord-scheduler
      resourceNamespace: {{ .Values.installation.namespace }}
    profiles:
      - pluginConfig:
        - name: NodeResourcesFit
          args:
            apiVersion: kubescheduler.config.k8s.io/v1beta2
            kind: NodeResourcesFitArgs
            scoringStrategy:
              type: LeastAllocated
              resources:
                - name: cpu
                  weight: 1
                - name: memory
                  weight: 1
                - name: "koordinator.sh/batch-cpu"
                  weight: 1
                - name: "koordinator.sh/batch-mem"
                  weight: 1
        - name: LoadAwareScheduling
          args:
            apiVersion: kubescheduler.config.k8s.io/v1beta2
            kind: LoadAwareSchedulingArgs
            filterExpiredNodeMetrics: true
            nodeMetricExpirationSeconds: 300
            resourceWeights:
              cpu: 1
              memory: 1
            usageThresholds:
              cpu: 85
              memory: 70
            estimatedScalingFactors:
              cpu: 80
              memory: 70
        plugins:
          queueSort:
            enabled:
              - name: Coscheduling
            disabled:
              - name: "*"
          preFilter:
            enabled:
              - name: NodeNUMAResource
              - name: Reservation
              - name: Coscheduling
          filter:
            enabled:
              - name: LoadAwareScheduling
              - name: NodeNUMAResource
              - name: Reservation
          postFilter:
            disabled:
              - name: "*"
            enabled:
              - name: Reservation
              - name: Coscheduling
{{- if semverCompare "<= 1.20-0" .Capabilities.KubeVersion.Version }} 
              - name: CompatibleDefaultPreemption
{{- else }}
              - name: DefaultPreemption
{{- end }}
          preScore:
            enabled:
              - name: Reservation
          score:
            enabled:
              - name: LoadAwareScheduling
                weight: 1
              - name: NodeNUMAResource
                weight: 1
              - name: Reservation
                weight: 5000
          reserve:
            enabled:
              - name: LoadAwareScheduling
              - name: NodeNUMAResource
              - name: Reservation
              - name: Coscheduling
          permit:
            enabled:
              - name: Coscheduling
          preBind:
            enabled:
              - name: NodeNUMAResource
              - name: Reservation
          bind:
            disabled:
              - name: "*"
            enabled:
              - name: Reservation
              - name: DefaultBinder
          postBind:
            enabled:
              - name: Coscheduling
        schedulerName: koord-scheduler