apiVersion: v1
kind: ConfigMap
metadata:
  name: koord-scheduler-config
  namespace: {{ .Values.installation.namespace }}
data:
  koord-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    profiles:
      - pluginConfig:
        - args:
            apiVersion: kubescheduler.config.k8s.io/v1beta2
            kind: NodeResourcesFitArgs
            scoringStrategy:
              type: LeastAllocated
              resources:
                - name: cpu
                  weight: 1
                - name: memory
                  weight: 1
                - name: "koordinator.sh/batch-cpu"
                  weight: 1
                - name: "koordinator.sh/batch-mem"
                  weight: 1
          name: NodeResourcesFit
        - args:
            apiVersion: kubescheduler.config.k8s.io/v1beta2
            kind: LoadAwareSchedulingArgs
            filterExpiredNodeMetrics: true
            nodeMetricExpirationSeconds: 300
            resourceWeights:
              cpu: 1
              memory: 1
            usageThresholds:
              cpu: 75
              memory: 85
            estimatedScalingFactors:
              cpu: 80
              memory: 70
          name: LoadAwareScheduling
        plugins:
          filter:
            enabled:
              - name: LoadAwareScheduling
                weight: 0
          reserve:
            enabled:
              - name: LoadAwareScheduling
                weight: 0
          score:
            enabled:
              - name: LoadAwareScheduling
                weight: 1000
        schedulerName: koord-scheduler